---
run:
  concurrency: 6
  timeout: 10m
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
  # Exclude previously existing issues from the report
  # new: true
  # new-from-rev: HEAD
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose  # Temporarily disabled.
    - depguard
    - dogsled
    #- errcheck  # Temporarily disabled.
    - errorlint
    - exhaustive
    - exportloopref
    - gci
    #- gochecknoinits  # Temporarily disabled.
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    #- goerr113  # Temporarily disabled.
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    #- lll  # Temporarily disabled.
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - predeclared
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    #- wrapcheck  # Temporarily disabled.
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    # https://golangci-lint.run/usage/linters/#exhaustive
    default-signifies-exhaustive: true
  godot:
    exclude:
      - "^ -- "
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ossf/malicious-packages)
  gocritic:
    enabled-checks:
      # Diagnostic
      - appendAssign
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagName
      - nilValReturn
      - weakCond
      - octalLiteral

      # Performance
      - appendCombine
      #- hugeParam  # Crashing.
      - rangeExprCopy
      - rangeValCopy

      # Style
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - commentedOutImport
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - singleCaseSwitch
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock

