// Copyright 2026 Malicious Packages Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: malicious_packages.proto

//go:build !protoopaque

package proto

import (
	osvschema "github.com/ossf/osv-schema/bindings/go/osvschema"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Indicators_File_Source int32

const (
	Indicators_File_UNSPECIFIED     Indicators_File_Source = 0
	Indicators_File_PACKAGE_ARCHIVE Indicators_File_Source = 1
	Indicators_File_DROPPED         Indicators_File_Source = 2
	Indicators_File_IN_MEMORY       Indicators_File_Source = 3
)

// Enum value maps for Indicators_File_Source.
var (
	Indicators_File_Source_name = map[int32]string{
		0: "SOURCE_UNSPECIFIED",
		1: "PACKAGE_ARCHIVE",
		2: "DROPPED",
		3: "IN_MEMORY",
	}
	Indicators_File_Source_value = map[string]int32{
		"SOURCE_UNSPECIFIED": 0,
		"PACKAGE_ARCHIVE":    1,
		"DROPPED":            2,
		"IN_MEMORY":          3,
	}
)

func (x Indicators_File_Source) Enum() *Indicators_File_Source {
	p := new(Indicators_File_Source)
	*p = x
	return p
}

func (x Indicators_File_Source) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Indicators_File_Source) Descriptor() protoreflect.EnumDescriptor {
	return file_malicious_packages_proto_enumTypes[0].Descriptor()
}

func (Indicators_File_Source) Type() protoreflect.EnumType {
	return &file_malicious_packages_proto_enumTypes[0]
}

func (x Indicators_File_Source) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// OriginRef is used to represent one origin OSV report that was ingested and
// merged together to produce the individual OSV report the ref appears in.
type OriginRef struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// The source where the report for this origin was ingested from.
	Source string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	// The SHA256 hex digest of the origin report itself.
	ShaSum string `protobuf:"bytes,2,opt,name=sha_sum,json=sha256" json:"sha_sum,omitempty"`
	// The RFC3339 timestamp indicating when this origin was imported from the
	// source.
	ImportTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=import_time" json:"import_time,omitempty"`
	// The RFC3339 timestamp indicating when this origin was modified.
	ModifiedTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=modified_time" json:"modified_time,omitempty"`
	// The OSV ID of the orign report, if it is present.
	Id string `protobuf:"bytes,5,opt,name=id" json:"id,omitempty"`
	// The OSV ranges in the origin affected record.
	Ranges []*osvschema.Range `protobuf:"bytes,6,rep,name=ranges" json:"ranges,omitempty"`
	// The OSV versions in the origin affected record.
	Versions      []string `protobuf:"bytes,7,rep,name=versions" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginRef) Reset() {
	*x = OriginRef{}
	mi := &file_malicious_packages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginRef) ProtoMessage() {}

func (x *OriginRef) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OriginRef) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OriginRef) GetShaSum() string {
	if x != nil {
		return x.ShaSum
	}
	return ""
}

func (x *OriginRef) GetImportTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ImportTime
	}
	return nil
}

func (x *OriginRef) GetModifiedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedTime
	}
	return nil
}

func (x *OriginRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OriginRef) GetRanges() []*osvschema.Range {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *OriginRef) GetVersions() []string {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *OriginRef) SetSource(v string) {
	x.Source = v
}

func (x *OriginRef) SetShaSum(v string) {
	x.ShaSum = v
}

func (x *OriginRef) SetImportTime(v *timestamppb.Timestamp) {
	x.ImportTime = v
}

func (x *OriginRef) SetModifiedTime(v *timestamppb.Timestamp) {
	x.ModifiedTime = v
}

func (x *OriginRef) SetId(v string) {
	x.Id = v
}

func (x *OriginRef) SetRanges(v []*osvschema.Range) {
	x.Ranges = v
}

func (x *OriginRef) SetVersions(v []string) {
	x.Versions = v
}

func (x *OriginRef) HasImportTime() bool {
	if x == nil {
		return false
	}
	return x.ImportTime != nil
}

func (x *OriginRef) HasModifiedTime() bool {
	if x == nil {
		return false
	}
	return x.ModifiedTime != nil
}

func (x *OriginRef) ClearImportTime() {
	x.ImportTime = nil
}

func (x *OriginRef) ClearModifiedTime() {
	x.ModifiedTime = nil
}

type OriginRef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The source where the report for this origin was ingested from.
	Source string
	// The SHA256 hex digest of the origin report itself.
	ShaSum string
	// The RFC3339 timestamp indicating when this origin was imported from the
	// source.
	ImportTime *timestamppb.Timestamp
	// The RFC3339 timestamp indicating when this origin was modified.
	ModifiedTime *timestamppb.Timestamp
	// The OSV ID of the orign report, if it is present.
	Id string
	// The OSV ranges in the origin affected record.
	Ranges []*osvschema.Range
	// The OSV versions in the origin affected record.
	Versions []string
}

func (b0 OriginRef_builder) Build() *OriginRef {
	m0 := &OriginRef{}
	b, x := &b0, m0
	_, _ = b, x
	x.Source = b.Source
	x.ShaSum = b.ShaSum
	x.ImportTime = b.ImportTime
	x.ModifiedTime = b.ModifiedTime
	x.Id = b.Id
	x.Ranges = b.Ranges
	x.Versions = b.Versions
	return m0
}

type Indicators struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// A set of domains the malicious package may resolve or connect to while
	// executing.
	Domains []string `protobuf:"bytes,1,rep,name=domains" json:"domains,omitempty"`
	// A set of IPs the malicious package may connect to while executing.
	Ips []string `protobuf:"bytes,2,rep,name=ips" json:"ips,omitempty"`
	// A set of URLs the malicious pacakge may requests while executing.
	Urls []string `protobuf:"bytes,3,rep,name=urls" json:"urls,omitempty"`
	// A set of files that are created or accessed during the execution of the
	// malicious package that are specific to the malicious package.
	Files []*Indicators_File `protobuf:"bytes,4,rep,name=files" json:"files,omitempty"`
	// Unsupported fields that are unspecified.
	UnsupportedStrings []string `protobuf:"bytes,5,rep,name=unsupported_strings,json=strings" json:"unsupported_strings,omitempty"`
	UnsupportedHashes  []string `protobuf:"bytes,6,rep,name=unsupported_hashes,json=hashes" json:"unsupported_hashes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Indicators) Reset() {
	*x = Indicators{}
	mi := &file_malicious_packages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicators) ProtoMessage() {}

func (x *Indicators) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Indicators) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *Indicators) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *Indicators) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *Indicators) GetFiles() []*Indicators_File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Indicators) GetUnsupportedStrings() []string {
	if x != nil {
		return x.UnsupportedStrings
	}
	return nil
}

func (x *Indicators) GetUnsupportedHashes() []string {
	if x != nil {
		return x.UnsupportedHashes
	}
	return nil
}

func (x *Indicators) SetDomains(v []string) {
	x.Domains = v
}

func (x *Indicators) SetIps(v []string) {
	x.Ips = v
}

func (x *Indicators) SetUrls(v []string) {
	x.Urls = v
}

func (x *Indicators) SetFiles(v []*Indicators_File) {
	x.Files = v
}

func (x *Indicators) SetUnsupportedStrings(v []string) {
	x.UnsupportedStrings = v
}

func (x *Indicators) SetUnsupportedHashes(v []string) {
	x.UnsupportedHashes = v
}

type Indicators_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A set of domains the malicious package may resolve or connect to while
	// executing.
	Domains []string
	// A set of IPs the malicious package may connect to while executing.
	Ips []string
	// A set of URLs the malicious pacakge may requests while executing.
	Urls []string
	// A set of files that are created or accessed during the execution of the
	// malicious package that are specific to the malicious package.
	Files []*Indicators_File
	// Unsupported fields that are unspecified.
	UnsupportedStrings []string
	UnsupportedHashes  []string
}

func (b0 Indicators_builder) Build() *Indicators {
	m0 := &Indicators{}
	b, x := &b0, m0
	_, _ = b, x
	x.Domains = b.Domains
	x.Ips = b.Ips
	x.Urls = b.Urls
	x.Files = b.Files
	x.UnsupportedStrings = b.UnsupportedStrings
	x.UnsupportedHashes = b.UnsupportedHashes
	return m0
}

type CWE struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	CweId         string                 `protobuf:"bytes,1,opt,name=cwe_id,json=cweId" json:"cwe_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CWE) Reset() {
	*x = CWE{}
	mi := &file_malicious_packages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CWE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CWE) ProtoMessage() {}

func (x *CWE) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CWE) GetCweId() string {
	if x != nil {
		return x.CweId
	}
	return ""
}

func (x *CWE) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CWE) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CWE) SetCweId(v string) {
	x.CweId = v
}

func (x *CWE) SetName(v string) {
	x.Name = v
}

func (x *CWE) SetDescription(v string) {
	x.Description = v
}

type CWE_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CweId       string
	Name        string
	Description string
}

func (b0 CWE_builder) Build() *CWE {
	m0 := &CWE{}
	b, x := &b0, m0
	_, _ = b, x
	x.CweId = b.CweId
	x.Name = b.Name
	x.Description = b.Description
	return m0
}

type DatabaseSpecificAffected struct {
	state                 protoimpl.MessageState `protogen:"hybrid.v1"`
	Cwes                  []*CWE                 `protobuf:"bytes,1,rep,name=cwes" json:"cwes,omitempty"`
	UnsupportedIocs       *Indicators            `protobuf:"bytes,2,opt,name=unsupported_iocs,json=unsupportedIocs" json:"unsupported_iocs,omitempty"`
	UnsupportedGhsa       string                 `protobuf:"bytes,3,opt,name=unsupported_ghsa,json=ghsa" json:"unsupported_ghsa,omitempty"`
	UnsupportedIndicators *structpb.Struct       `protobuf:"bytes,4,opt,name=unsupported_indicators,json=indicators" json:"unsupported_indicators,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DatabaseSpecificAffected) Reset() {
	*x = DatabaseSpecificAffected{}
	mi := &file_malicious_packages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseSpecificAffected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseSpecificAffected) ProtoMessage() {}

func (x *DatabaseSpecificAffected) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DatabaseSpecificAffected) GetCwes() []*CWE {
	if x != nil {
		return x.Cwes
	}
	return nil
}

func (x *DatabaseSpecificAffected) GetUnsupportedIocs() *Indicators {
	if x != nil {
		return x.UnsupportedIocs
	}
	return nil
}

func (x *DatabaseSpecificAffected) GetUnsupportedGhsa() string {
	if x != nil {
		return x.UnsupportedGhsa
	}
	return ""
}

func (x *DatabaseSpecificAffected) GetUnsupportedIndicators() *structpb.Struct {
	if x != nil {
		return x.UnsupportedIndicators
	}
	return nil
}

func (x *DatabaseSpecificAffected) SetCwes(v []*CWE) {
	x.Cwes = v
}

func (x *DatabaseSpecificAffected) SetUnsupportedIocs(v *Indicators) {
	x.UnsupportedIocs = v
}

func (x *DatabaseSpecificAffected) SetUnsupportedGhsa(v string) {
	x.UnsupportedGhsa = v
}

func (x *DatabaseSpecificAffected) SetUnsupportedIndicators(v *structpb.Struct) {
	x.UnsupportedIndicators = v
}

func (x *DatabaseSpecificAffected) HasUnsupportedIocs() bool {
	if x == nil {
		return false
	}
	return x.UnsupportedIocs != nil
}

func (x *DatabaseSpecificAffected) HasUnsupportedIndicators() bool {
	if x == nil {
		return false
	}
	return x.UnsupportedIndicators != nil
}

func (x *DatabaseSpecificAffected) ClearUnsupportedIocs() {
	x.UnsupportedIocs = nil
}

func (x *DatabaseSpecificAffected) ClearUnsupportedIndicators() {
	x.UnsupportedIndicators = nil
}

type DatabaseSpecificAffected_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cwes                  []*CWE
	UnsupportedIocs       *Indicators
	UnsupportedGhsa       string
	UnsupportedIndicators *structpb.Struct
}

func (b0 DatabaseSpecificAffected_builder) Build() *DatabaseSpecificAffected {
	m0 := &DatabaseSpecificAffected{}
	b, x := &b0, m0
	_, _ = b, x
	x.Cwes = b.Cwes
	x.UnsupportedIocs = b.UnsupportedIocs
	x.UnsupportedGhsa = b.UnsupportedGhsa
	x.UnsupportedIndicators = b.UnsupportedIndicators
	return m0
}

type Affected struct {
	state            protoimpl.MessageState    `protogen:"hybrid.v1"`
	DatabaseSpecific *DatabaseSpecificAffected `protobuf:"bytes,5,opt,name=database_specific" json:"database_specific,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Affected) Reset() {
	*x = Affected{}
	mi := &file_malicious_packages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Affected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affected) ProtoMessage() {}

func (x *Affected) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Affected) GetDatabaseSpecific() *DatabaseSpecificAffected {
	if x != nil {
		return x.DatabaseSpecific
	}
	return nil
}

func (x *Affected) SetDatabaseSpecific(v *DatabaseSpecificAffected) {
	x.DatabaseSpecific = v
}

func (x *Affected) HasDatabaseSpecific() bool {
	if x == nil {
		return false
	}
	return x.DatabaseSpecific != nil
}

func (x *Affected) ClearDatabaseSpecific() {
	x.DatabaseSpecific = nil
}

type Affected_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DatabaseSpecific *DatabaseSpecificAffected
}

func (b0 Affected_builder) Build() *Affected {
	m0 := &Affected{}
	b, x := &b0, m0
	_, _ = b, x
	x.DatabaseSpecific = b.DatabaseSpecific
	return m0
}

type DatabaseSpecific struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Origins       []*OriginRef           `protobuf:"bytes,1,rep,name=origins,json=malicious-packages-origins" json:"origins,omitempty"`
	Iocs          *Indicators            `protobuf:"bytes,2,opt,name=iocs" json:"iocs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseSpecific) Reset() {
	*x = DatabaseSpecific{}
	mi := &file_malicious_packages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseSpecific) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseSpecific) ProtoMessage() {}

func (x *DatabaseSpecific) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DatabaseSpecific) GetOrigins() []*OriginRef {
	if x != nil {
		return x.Origins
	}
	return nil
}

func (x *DatabaseSpecific) GetIocs() *Indicators {
	if x != nil {
		return x.Iocs
	}
	return nil
}

func (x *DatabaseSpecific) SetOrigins(v []*OriginRef) {
	x.Origins = v
}

func (x *DatabaseSpecific) SetIocs(v *Indicators) {
	x.Iocs = v
}

func (x *DatabaseSpecific) HasIocs() bool {
	if x == nil {
		return false
	}
	return x.Iocs != nil
}

func (x *DatabaseSpecific) ClearIocs() {
	x.Iocs = nil
}

type DatabaseSpecific_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Origins []*OriginRef
	Iocs    *Indicators
}

func (b0 DatabaseSpecific_builder) Build() *DatabaseSpecific {
	m0 := &DatabaseSpecific{}
	b, x := &b0, m0
	_, _ = b, x
	x.Origins = b.Origins
	x.Iocs = b.Iocs
	return m0
}

type Vulnerability struct {
	state            protoimpl.MessageState `protogen:"hybrid.v1"`
	Affected         []*Affected            `protobuf:"bytes,17,rep,name=affected" json:"affected,omitempty"`
	DatabaseSpecific *DatabaseSpecific      `protobuf:"bytes,15,opt,name=database_specific" json:"database_specific,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Vulnerability) Reset() {
	*x = Vulnerability{}
	mi := &file_malicious_packages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vulnerability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vulnerability) ProtoMessage() {}

func (x *Vulnerability) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Vulnerability) GetAffected() []*Affected {
	if x != nil {
		return x.Affected
	}
	return nil
}

func (x *Vulnerability) GetDatabaseSpecific() *DatabaseSpecific {
	if x != nil {
		return x.DatabaseSpecific
	}
	return nil
}

func (x *Vulnerability) SetAffected(v []*Affected) {
	x.Affected = v
}

func (x *Vulnerability) SetDatabaseSpecific(v *DatabaseSpecific) {
	x.DatabaseSpecific = v
}

func (x *Vulnerability) HasDatabaseSpecific() bool {
	if x == nil {
		return false
	}
	return x.DatabaseSpecific != nil
}

func (x *Vulnerability) ClearDatabaseSpecific() {
	x.DatabaseSpecific = nil
}

type Vulnerability_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Affected         []*Affected
	DatabaseSpecific *DatabaseSpecific
}

func (b0 Vulnerability_builder) Build() *Vulnerability {
	m0 := &Vulnerability{}
	b, x := &b0, m0
	_, _ = b, x
	x.Affected = b.Affected
	x.DatabaseSpecific = b.DatabaseSpecific
	return m0
}

type Indicators_File struct {
	state protoimpl.MessageState `protogen:"hybrid.v1"`
	// Paths lists the file names (relative or absolute) at which the file was
	// observed — the same content can appear in several places. Optional for a
	// file that never hit disk (source "IN_MEMORY"), which is identified by its
	// digest alone.
	Paths []string `protobuf:"bytes,1,rep,name=paths" json:"paths,omitempty"`
	// An optional free text note describing the file.
	Note string `protobuf:"bytes,2,opt,name=note" json:"note,omitempty"`
	// Source records where the file came from.
	Source Indicators_File_Source `protobuf:"varint,3,opt,name=source,enum=ossf.malicious_packages.Indicators_File_Source" json:"source,omitempty"`
	// Digests holds one or more content hashes of the file.
	Digests       *Indicators_File_Digests `protobuf:"bytes,4,opt,name=digests" json:"digests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Indicators_File) Reset() {
	*x = Indicators_File{}
	mi := &file_malicious_packages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicators_File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicators_File) ProtoMessage() {}

func (x *Indicators_File) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Indicators_File) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *Indicators_File) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Indicators_File) GetSource() Indicators_File_Source {
	if x != nil {
		return x.Source
	}
	return Indicators_File_UNSPECIFIED
}

func (x *Indicators_File) GetDigests() *Indicators_File_Digests {
	if x != nil {
		return x.Digests
	}
	return nil
}

func (x *Indicators_File) SetPaths(v []string) {
	x.Paths = v
}

func (x *Indicators_File) SetNote(v string) {
	x.Note = v
}

func (x *Indicators_File) SetSource(v Indicators_File_Source) {
	x.Source = v
}

func (x *Indicators_File) SetDigests(v *Indicators_File_Digests) {
	x.Digests = v
}

func (x *Indicators_File) HasDigests() bool {
	if x == nil {
		return false
	}
	return x.Digests != nil
}

func (x *Indicators_File) ClearDigests() {
	x.Digests = nil
}

type Indicators_File_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Paths lists the file names (relative or absolute) at which the file was
	// observed — the same content can appear in several places. Optional for a
	// file that never hit disk (source "IN_MEMORY"), which is identified by its
	// digest alone.
	Paths []string
	// An optional free text note describing the file.
	Note string
	// Source records where the file came from.
	Source Indicators_File_Source
	// Digests holds one or more content hashes of the file.
	Digests *Indicators_File_Digests
}

func (b0 Indicators_File_builder) Build() *Indicators_File {
	m0 := &Indicators_File{}
	b, x := &b0, m0
	_, _ = b, x
	x.Paths = b.Paths
	x.Note = b.Note
	x.Source = b.Source
	x.Digests = b.Digests
	return m0
}

// A set of digests for the entire file.
type Indicators_File_Digests struct {
	state         protoimpl.MessageState `protogen:"hybrid.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256" json:"sha256,omitempty"`
	Sha1          string                 `protobuf:"bytes,2,opt,name=sha1" json:"sha1,omitempty"`
	Md5           string                 `protobuf:"bytes,3,opt,name=md5" json:"md5,omitempty"`
	Tlsh          string                 `protobuf:"bytes,4,opt,name=tlsh" json:"tlsh,omitempty"`
	Ssdeep        string                 `protobuf:"bytes,5,opt,name=ssdeep" json:"ssdeep,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Indicators_File_Digests) Reset() {
	*x = Indicators_File_Digests{}
	mi := &file_malicious_packages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicators_File_Digests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicators_File_Digests) ProtoMessage() {}

func (x *Indicators_File_Digests) ProtoReflect() protoreflect.Message {
	mi := &file_malicious_packages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Indicators_File_Digests) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Indicators_File_Digests) GetSha1() string {
	if x != nil {
		return x.Sha1
	}
	return ""
}

func (x *Indicators_File_Digests) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *Indicators_File_Digests) GetTlsh() string {
	if x != nil {
		return x.Tlsh
	}
	return ""
}

func (x *Indicators_File_Digests) GetSsdeep() string {
	if x != nil {
		return x.Ssdeep
	}
	return ""
}

func (x *Indicators_File_Digests) SetSha256(v string) {
	x.Sha256 = v
}

func (x *Indicators_File_Digests) SetSha1(v string) {
	x.Sha1 = v
}

func (x *Indicators_File_Digests) SetMd5(v string) {
	x.Md5 = v
}

func (x *Indicators_File_Digests) SetTlsh(v string) {
	x.Tlsh = v
}

func (x *Indicators_File_Digests) SetSsdeep(v string) {
	x.Ssdeep = v
}

type Indicators_File_Digests_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sha256 string
	Sha1   string
	Md5    string
	Tlsh   string
	Ssdeep string
}

func (b0 Indicators_File_Digests_builder) Build() *Indicators_File_Digests {
	m0 := &Indicators_File_Digests{}
	b, x := &b0, m0
	_, _ = b, x
	x.Sha256 = b.Sha256
	x.Sha1 = b.Sha1
	x.Md5 = b.Md5
	x.Tlsh = b.Tlsh
	x.Ssdeep = b.Ssdeep
	return m0
}

var File_malicious_packages_proto protoreflect.FileDescriptor

const file_malicious_packages_proto_rawDesc = "" +
	"\n" +
	"\x18malicious_packages.proto\x12\x17ossf.malicious_packages\x1a!google/protobuf/go_features.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dosv/proto/vulnerability.proto\"\x8e\x02\n" +
	"\tOriginRef\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x17\n" +
	"\asha_sum\x18\x02 \x01(\tR\x06sha256\x12<\n" +
	"\vimport_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vimport_time\x12@\n" +
	"\rmodified_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rmodified_time\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\"\n" +
	"\x06ranges\x18\x06 \x03(\v2\n" +
	".osv.RangeR\x06ranges\x12\x1a\n" +
	"\bversions\x18\a \x03(\tR\bversionsX\x02\"\xee\x04\n" +
	"\n" +
	"Indicators\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains\x12\x10\n" +
	"\x03ips\x18\x02 \x03(\tR\x03ips\x12\x12\n" +
	"\x04urls\x18\x03 \x03(\tR\x04urls\x12>\n" +
	"\x05files\x18\x04 \x03(\v2(.ossf.malicious_packages.Indicators.FileR\x05files\x12$\n" +
	"\x13unsupported_strings\x18\x05 \x03(\tR\astrings\x12\"\n" +
	"\x12unsupported_hashes\x18\x06 \x03(\tR\x06hashes\x1a\x93\x03\n" +
	"\x04File\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\x12G\n" +
	"\x06source\x18\x03 \x01(\x0e2/.ossf.malicious_packages.Indicators.File.SourceR\x06source\x12J\n" +
	"\adigests\x18\x04 \x01(\v20.ossf.malicious_packages.Indicators.File.DigestsR\adigests\x1au\n" +
	"\aDigests\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x12\n" +
	"\x04sha1\x18\x02 \x01(\tR\x04sha1\x12\x10\n" +
	"\x03md5\x18\x03 \x01(\tR\x03md5\x12\x12\n" +
	"\x04tlsh\x18\x04 \x01(\tR\x04tlsh\x12\x16\n" +
	"\x06ssdeep\x18\x05 \x01(\tR\x06ssdeepX\x02\"S\n" +
	"\x06Source\x12\x16\n" +
	"\x12SOURCE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPACKAGE_ARCHIVE\x10\x01\x12\v\n" +
	"\aDROPPED\x10\x02\x12\r\n" +
	"\tIN_MEMORY\x10\x030\x02X\x02X\x02\"T\n" +
	"\x03CWE\x12\x15\n" +
	"\x06cwe_id\x18\x01 \x01(\tR\x05cweId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionX\x02\"\x83\x02\n" +
	"\x18DatabaseSpecificAffected\x120\n" +
	"\x04cwes\x18\x01 \x03(\v2\x1c.ossf.malicious_packages.CWER\x04cwes\x12N\n" +
	"\x10unsupported_iocs\x18\x02 \x01(\v2#.ossf.malicious_packages.IndicatorsR\x0funsupportedIocs\x12\x1e\n" +
	"\x10unsupported_ghsa\x18\x03 \x01(\tR\x04ghsa\x12C\n" +
	"\x16unsupported_indicators\x18\x04 \x01(\v2\x17.google.protobuf.StructR\n" +
	"indicatorsX\x02\"m\n" +
	"\bAffected\x12_\n" +
	"\x11database_specific\x18\x05 \x01(\v21.ossf.malicious_packages.DatabaseSpecificAffectedR\x11database_specificX\x02\"\x9c\x01\n" +
	"\x10DatabaseSpecific\x12O\n" +
	"\aorigins\x18\x01 \x03(\v2\".ossf.malicious_packages.OriginRefR\x1amalicious-packages-origins\x127\n" +
	"\x04iocs\x18\x02 \x01(\v2#.ossf.malicious_packages.IndicatorsR\x04iocs\"\xa9\x01\n" +
	"\rVulnerability\x12=\n" +
	"\baffected\x18\x11 \x03(\v2!.ossf.malicious_packages.AffectedR\baffected\x12W\n" +
	"\x11database_specific\x18\x0f \x01(\v2).ossf.malicious_packages.DatabaseSpecificR\x11database_specificX\x02B6Z(github.com/ossf/malicious-packages/proto\x92\x03\t\xd2>\x04\x10\x02\x18\x03\b\x02b\beditionsp\xe9\a"

var file_malicious_packages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_malicious_packages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_malicious_packages_proto_goTypes = []any{
	(Indicators_File_Source)(0),      // 0: ossf.malicious_packages.Indicators.File.Source
	(*OriginRef)(nil),                // 1: ossf.malicious_packages.OriginRef
	(*Indicators)(nil),               // 2: ossf.malicious_packages.Indicators
	(*CWE)(nil),                      // 3: ossf.malicious_packages.CWE
	(*DatabaseSpecificAffected)(nil), // 4: ossf.malicious_packages.DatabaseSpecificAffected
	(*Affected)(nil),                 // 5: ossf.malicious_packages.Affected
	(*DatabaseSpecific)(nil),         // 6: ossf.malicious_packages.DatabaseSpecific
	(*Vulnerability)(nil),            // 7: ossf.malicious_packages.Vulnerability
	(*Indicators_File)(nil),          // 8: ossf.malicious_packages.Indicators.File
	(*Indicators_File_Digests)(nil),  // 9: ossf.malicious_packages.Indicators.File.Digests
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
	(*osvschema.Range)(nil),          // 11: osv.Range
	(*structpb.Struct)(nil),          // 12: google.protobuf.Struct
}
var file_malicious_packages_proto_depIdxs = []int32{
	10, // 0: ossf.malicious_packages.OriginRef.import_time:type_name -> google.protobuf.Timestamp
	10, // 1: ossf.malicious_packages.OriginRef.modified_time:type_name -> google.protobuf.Timestamp
	11, // 2: ossf.malicious_packages.OriginRef.ranges:type_name -> osv.Range
	8,  // 3: ossf.malicious_packages.Indicators.files:type_name -> ossf.malicious_packages.Indicators.File
	3,  // 4: ossf.malicious_packages.DatabaseSpecificAffected.cwes:type_name -> ossf.malicious_packages.CWE
	2,  // 5: ossf.malicious_packages.DatabaseSpecificAffected.unsupported_iocs:type_name -> ossf.malicious_packages.Indicators
	12, // 6: ossf.malicious_packages.DatabaseSpecificAffected.unsupported_indicators:type_name -> google.protobuf.Struct
	4,  // 7: ossf.malicious_packages.Affected.database_specific:type_name -> ossf.malicious_packages.DatabaseSpecificAffected
	1,  // 8: ossf.malicious_packages.DatabaseSpecific.origins:type_name -> ossf.malicious_packages.OriginRef
	2,  // 9: ossf.malicious_packages.DatabaseSpecific.iocs:type_name -> ossf.malicious_packages.Indicators
	5,  // 10: ossf.malicious_packages.Vulnerability.affected:type_name -> ossf.malicious_packages.Affected
	6,  // 11: ossf.malicious_packages.Vulnerability.database_specific:type_name -> ossf.malicious_packages.DatabaseSpecific
	0,  // 12: ossf.malicious_packages.Indicators.File.source:type_name -> ossf.malicious_packages.Indicators.File.Source
	9,  // 13: ossf.malicious_packages.Indicators.File.digests:type_name -> ossf.malicious_packages.Indicators.File.Digests
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_malicious_packages_proto_init() }
func file_malicious_packages_proto_init() {
	if File_malicious_packages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_malicious_packages_proto_rawDesc), len(file_malicious_packages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_malicious_packages_proto_goTypes,
		DependencyIndexes: file_malicious_packages_proto_depIdxs,
		EnumInfos:         file_malicious_packages_proto_enumTypes,
		MessageInfos:      file_malicious_packages_proto_msgTypes,
	}.Build()
	File_malicious_packages_proto = out.File
	file_malicious_packages_proto_goTypes = nil
	file_malicious_packages_proto_depIdxs = nil
}
