name: "Protobuf Continuous Integration"

on:
  push:
    branches:
      - main
    paths:
      - 'proto/**'
  pull_request:
    paths:
      - 'proto/**'

permissions:
  contents: read

jobs:
  run-proto-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: 'go.mod'
    - name: Install protoc
      uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
    - name: Install Go Protobuf Plugins
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    - name: Generate protobuf code
      run: make gen-protos
    - name: Verify no changes
      run: |
        # If there are modified or untracked files, git status will not be empty
        if [ -n "$(git status --porcelain)" ]; then
          echo "::error::Generated protobuf files are out of sync your .proto files."
          echo "Please run `make gen-protos` locally and commit the updated files."
          git status
          git diff
          exit 1
        else
          echo "Generated protobuf files are up to date."
        fi
